[package]
name = "basic_rust_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["derive"] }
clap = { version = "4.5.51", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["from"] }
